### ISSUE TITLE
Revert back to normal stb image

### ISSUE THREAD

**Issue by uzkezbalakh** [jmendeth/dm500-satip#5]
Dear jmendeth..
im a noob.. need help to revert back to normal stb image (gemini, openpli etc)
dunno how do it as my dm500s refuse a telnet and FTP session.
Fortunately it can be SSH and SCP

How do i use command in SSH to reflash a gemini image for instance.. thanx for your help..

**Comment by mildsunrise** [comment]
The easiest way is through DreamUp.

Or, you can copy the image into the DM500S (i.e. with scp):

~~~ bash
scp your-image.img 192.168.1.34:/tmp/flash.img
~~~

Then SSH into the box and flash it with:

~~~ bash
flashcp -v /tmp/flash.img /dev/mtd0
~~~

**Comment by uzkezbalakh** [comment]
Thx jmendeth.. my DM500S is back to normal.. seems so easy with a genius like u..

**Comment by mildsunrise** [comment]
Glad to hear ^^
